name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
description: Forneça os parâmetros adicionais do job para a próxima execução
title: "[credit-data-science] Parameters_update"
labels: ["credit", "parameters-job"]

body:
  - type: checkboxes
    id: write_credit_engine
    attributes:
      label: "WRITE_CREDIT_ENGINE"
      description: "Escolha se ocorrerá ou não execução da task RatingUnifier"
      options:
        - label: "true"
        - label: "false"
    validations:
      required: true
  - type: checkboxes
    id: initial_date
    attributes:
      label: "Set INITIAL_DATE"
      description: "Choose whether to set the initial date."
      options:
        - label: "true"
        - label: "false"
    validations:
      required: true

  - type: input
    id: initial_date_value
    attributes:
      label: "Provide INITIAL_DATE"
      description: "Enter the initial date in YYYY-MM-DD format."
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
    condition: |
      if initial_date == 'true'
