name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
description: Forneça os parâmetros adicionais do job para a próxima execução
title: "[credit-data-science] Parameters_update"
labels: ["credit", "parameters-job"]

body:
  - type: checkboxes
    id: write_credit_engine
    attributes:
      label: "WRITE_CREDIT_ENGINE"
      description: "Escolha se ocorrerá ou não execução da task RatingUnifier"
      options:
        - label: "true"
        - label: "false"
    validations:
      required: true

  - type: input
    id: initial_date
    attributes:
      label: "INITIAL_DATE"
      description: "Escolha se a próxima execução usará o parâmetro INITIAL_DATE na task RevenueModel"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
