name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
description: Forneça os parâmetros adicionais do job para a próxima execução, caso necessário.
title: "[credit-data-science] Parameters_update"
labels: ["credit", "job-parameters"]

body:
  - type: checkboxes
    id: write_credit_engine
    attributes:
      label: "WRITE_CREDIT_ENGINE"
      options:
        - label: "Haverá a execução da task RatingUnifier? (Marque em caso afirmativo)"
      
  - type: checkboxes
    id: initial_date_check
    attributes:
      label: "INITIAL_DATE"
      options:
        - label: "Utilizar o parametro INITIAL_DATE na task RevenueModel? (Marque em caso afirmativo)"
      
  - type: input
    id: initial_date_setup
    attributes:
      label: "Qual a data para o INITIAL_DATE?"
      description: "Em caso afirmativo forneça a data para o parâmetro INITIAL_DATE "
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
