name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
on:
  # Trigger when an issue is opened or edited
  issues:
    types: [opened, edited]
  # Allow manual trigger via the GitHub UI, no inputs required
  workflow_dispatch:
jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get issue details and print labels
        run: |
              # Extract WRITE_CREDIT_ENGINE value
              if echo "${{ github.event.issue.body }}" | grep -q 'Haverá a execução da task RatingUnifier.*- \[x\]'; then
                WRITE_CREDIT_ENGINE="true"
              else
                WRITE_CREDIT_ENGINE="false" # Default value if not checked
              fi
              
              # Extract INITIAL_DATE_CHECK and INITIAL_DATE_SETUP
              if echo "${{ github.event.issue.body }}" | grep -q 'Utilizar o parametro INITIAL_DATE.*- \[x\]'; then
                INITIAL_DATE_CHECK="true"
                # Extract the date line after "Qual a data para o INITIAL_DATE?"
                INITIAL_DATE_SETUP=$(echo "${{ github.event.issue.body }}" | grep -A1 'Qual a data para o INITIAL_DATE' | tail -n1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                
                # Validate date format (YYYY-MM-DD)
                if [[ ! "$INITIAL_DATE_SETUP" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
                  echo "::warning::Invalid date format for INITIAL_DATE_SETUP: $INITIAL_DATE_SETUP"
                  INITIAL_DATE_CHECK="false"
                  INITIAL_DATE_SETUP=""
                fi
              else
                INITIAL_DATE_CHECK="false"
                INITIAL_DATE_SETUP=""
              fi
              
              # Output the values
              echo "WRITE_CREDIT_ENGINE=$WRITE_CREDIT_ENGINE" >> $GITHUB_OUTPUT
              echo "INITIAL_DATE_CHECK=$INITIAL_DATE_CHECK" >> $GITHUB_OUTPUT
              echo "INITIAL_DATE_SETUP=$INITIAL_DATE_SETUP" >> $GITHUB_OUTPUT
              
              echo "Parsed values:"
              echo "WRITE_CREDIT_ENGINE: $WRITE_CREDIT_ENGINE"
              echo "INITIAL_DATE_CHECK: $INITIAL_DATE_CHECK"
              echo "INITIAL_DATE_SETUP: $INITIAL_DATE_SETUP"
