name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
on:
  # Trigger when an issue is opened or edited
  issues:
    types: [opened, edited]
  # Allow manual trigger via the GitHub UI, no inputs required
  workflow_dispatch:
jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get issue details and print labels
        run: |
              # Debug: Print the full issue body to verify content
              echo "=== FULL ISSUE BODY ==="
              echo "${{ github.event.issue.body }}"
              echo "======================"
              
              # Extract WRITE_CREDIT_ENGINE value
              if echo "${{ github.event.issue.body }}" | grep -q '^- \[x\] Haverá a execução da task RatingUnifier? (Marque em caso afirmativo)'; then
                WRITE_CREDIT_ENGINE="true"
                echo "DEBUG: WRITE_CREDIT_ENGINE checkbox is checked"
              else
                WRITE_CREDIT_ENGINE="false"
                echo "DEBUG: WRITE_CREDIT_ENGINE checkbox is NOT checked"
              fi
              
              # Extract INITIAL_DATE_CHECK and INITIAL_DATE_SETUP
              if echo "${{ github.event.issue.body }}" | grep -q '^- \[x\] Utilizar o parametro INITIAL_DATE na task RevenueModel? (Marque em caso afirmativo)'; then
                INITIAL_DATE_CHECK="true"
                echo "DEBUG: INITIAL_DATE checkbox is checked"
                
                # Extract the date line - look for YYYY-MM-DD pattern after the question
                INITIAL_DATE_SETUP=$(echo "${{ github.event.issue.body }}" | grep -A1 '^### Qual a data para o INITIAL_DATE\?' | tail -n1 | grep -Eo '[0-9]{4}-[0-9]{2}-[0-9]{2}')
                
              else
                INITIAL_DATE_CHECK="false"
                echo "DEBUG: INITIAL_DATE_CHECK checkbox is NOT checked"
              fi

              # Output the values
              echo "WRITE_CREDIT_ENGINE=${WRITE_CREDIT_ENGINE}" >> $GITHUB_OUTPUT
              echo "INITIAL_DATE_CHECK=${INITIAL_DATE_CHECK}" >> $GITHUB_OUTPUT
              echo "INITIAL_DATE_SETUP=${INITIAL_DATE_SETUP}" >> $GITHUB_OUTPUT
              
              echo "=== FINAL PARSED VALUES ==="
              echo "WRITE_CREDIT_ENGINE: ${WRITE_CREDIT_ENGINE}"
              echo "INITIAL_DATE_CHECK: ${INITIAL_DATE_CHECK}"
              echo "INITIAL_DATE_SETUP: ${INITIAL_DATE_SETUP}"
                
