name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws

on:
  # Trigger when an issue is opened or edited
  issues:
    types: [opened, edited]

  # Allow manual trigger via the GitHub UI, no inputs required
  workflow_dispatch:

jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Display Debug Information
        run: |
          # If the action is triggered by a new issue, we will use the issue body
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "Debugging the issue body..."
            echo "Title: ${{ github.event.issue.title }}"
            echo "Labels: ${{ github.event.issue.labels }}"
            echo "Body: ${{ github.event.issue.body }}"
            
            # Parse the body for specific parameters
            WRITE_CREDIT_ENGINE=$(echo "${{ github.event.issue.body }}" | grep -o 'WRITE_CREDIT_ENGINE.*' | sed 's/.*WRITE_CREDIT_ENGINE: //')
            INITIAL_DATE_CHECK=$(echo "${{ github.event.issue.body }}" | grep -o 'INITIAL_DATE.*' | sed 's/.*INITIAL_DATE: //')
            INITIAL_DATE_SETUP=$(echo "${{ github.event.issue.body }}" | grep -o 'INITIAL_DATE_SETUP.*' | sed 's/.*INITIAL_DATE_SETUP: //')
          else
            # If manually triggered, we will skip body parsing and just log that it's been triggered
            echo "Manual trigger activated - no body to parse."
            WRITE_CREDIT_ENGINE="Not Provided"
            INITIAL_DATE_CHECK="Not Provided"
            INITIAL_DATE_SETUP="Not Provided"
          fi
          
          echo "WRITE_CREDIT_ENGINE: $WRITE_CREDIT_ENGINE"
          echo "INITIAL_DATE_CHECK: $INITIAL_DATE_CH
