name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws

on:
  # Trigger when an issue is opened or edited
  issues:
    types: [opened, edited]

  workflow_dispatch:

jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get issue details and print labels
        run: |
          echo "Fetching issue data and debugging..."

          # Fetch issue details using the issue trigger
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_LABELS="${{ github.event.issue.labels }}"

          # Always check the title and labels
          echo "Issue title: $ISSUE_TITLE"
          
          # Print the labels as an array (only the label names)
          echo "Issue labels as an array (only names):"
          for label in $(echo "$ISSUE_LABELS" | jq -r '.[].name'); do
            echo "Label: $label"
          done

          echo "Issue body: $ISSUE_BODY"

          # Parse and print specific parameters in the body if available
          WRITE_CREDIT_ENGINE=$(echo "$ISSUE_BODY" | grep -o 'WRITE_CREDIT_ENGINE.*' | sed 's/.*WRITE_CREDIT_ENGINE: //')
          INITIAL_DATE_CHECK=$(echo "$ISSUE_BODY" | grep -o 'INITIAL_DATE.*' | sed 's/.*INITIAL_DATE: //')
          INITIAL_DATE_SETUP=$(echo "$ISSUE_BODY" | grep -o 'INITIAL_DATE_SETUP.*' | sed 's/.*INITIAL_DATE_SETUP: //')

          echo "WRITE_CREDIT_ENGINE: $WRITE_CREDIT_ENGINE"
          echo "INITIAL_DATE_CHECK: $INITIAL_DATE_CHECK"
          echo "INITIAL_DATE_SETUP: $INITIAL_DATE_SETUP"

      - name: Log parameters for further analysis
        run: |
          echo "Final parameters:"
          echo "WRITE_CREDIT_ENGINE: $WRITE_CREDIT_ENGINE"
          echo "INITIAL_DATE_CHECK: $INITIAL_DATE_CHECK"
          echo "Initial date setup: $INITIAL_DATE_SETUP"
