name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws

on:
  # Trigger when an issue is opened or edited
  issues:
    types: [opened, edited]

  # Allow manual trigger via the GitHub UI, no inputs required
  workflow_dispatch:

jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Check for Issue and Debug Information
        run: |
          echo "Checking if the trigger is from an issue or manual..."

          # If triggered by an issue event
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            echo "Triggered by an issue event..."
            ISSUE_TITLE="${{ github.event.issue.title }}"
            ISSUE_BODY="${{ github.event.issue.body }}"
            ISSUE_LABELS="${{ github.event.issue.labels }}"

            # Check if the issue has the required labels and title
            echo "Issue title: $ISSUE_TITLE"
            echo "Issue labels: $ISSUE_LABELS"
            echo "Issue body: $ISSUE_BODY"

            if [[ "$ISSUE_TITLE" == *"[credit-data-science] Parameters_update"* ]]; then
              echo "This is a valid issue title."
            else
              echo "This is NOT a valid issue title."
            fi

            # Check for specific label
            if [[ "$ISSUE_LABELS" == *"credit"* ]]; then
              echo "Valid label found: credit"
            else
              echo "No valid label 'credit' found."
            fi

            # Parse and print specific param
