name: ⚙️ Atualização de parâmetros do job credit_data_science-prod-v1-aws
on:
  workflow_dispatch: # This allows manual trigger via the GitHub UI
    inputs:
      write_credit_engine:
        description: 'Escolha se ocorrerá ou não execução da task RatingUnifier (true or false)'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      
      initial_date_check:
        description: 'Escolha se haverá utilização do parâmetro INITIAL_DATE na task RevenueModel (Sim or Não)'
        required: true
        default: 'Sim'
        type: choice
        options:
          - 'Sim'
          - 'Não'
      
      initial_date_setup:
        description: 'Se marcado como "Sim", forneça a data para o parâmetro INITIAL_DATE'
        required: false
        default: ''
        type: string

jobs:
  debug-parameters:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Display Debug Information
        run: |
          echo "Debugging the manual trigger parameters..."
          echo "write_credit_engine: ${{ github.event.inputs.write_credit_engine }}"
          echo "initial_date_check: ${{ github.event.inputs.initial_date_check }}"
          echo "initial_date_setup: ${{ github.event.inputs.initial_date_setup }}"
          
      - name: Debugging the manual trigger inputs
        run: |
          echo "Full manual input values:"
          echo "write_credit_engine: ${{ github.event.inputs.write_credit_engine }}"
          echo "initial_date_check: ${{ github.event.inputs.initial_date_check }}"
          echo "initial_date_setup: ${{ github.event.inputs.initial_date_setup }}"
          
      - name: Log parameters for further analysis
        run: |
          echo "Final parameters:"
          echo "WRITE_CREDIT_ENGINE: ${{ github.event.inputs.write_credit_engine }}"
