name: Update Reference Date to Next Monday

on:
  schedule:
    # Runs every Thursday at 9:00 AM UTC
    - cron: '0 9 * * 3'
  # Optional: Allow manual workflow dispatch
  workflow_dispatch:

# Add these permissions
permissions:
  contents: write
  pull-requests: write
  
jobs:
  update-reference-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dateutil

      - name: Update reference date to next Monday
        id: update-date
        run: python .github/scripts/update_parameters.py
        shell: bash
        
      - name: Create branch and commit changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git checkout -b ${{ steps.update-date.outputs.branch_name }}
          git add .
          git commit -m "Update REFERENCE_DATE to ${{ steps.update-date.outputs.next_monday }}"
          git push origin ${{ steps.update-date.outputs.branch_name }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const nextMonday = '${{ steps.update-date.outputs.next_monday }}';
            const branchName = '${{ steps.update-date.outputs.branch_name }}';
            
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              owner,
              repo,
              title: `Update REFERENCE_DATE to ${nextMonday}`,
              body: `This automated PR updates the REFERENCE_DATE to the next Monday (${nextMonday}).\n\nAutomatically generated by the Update Reference Date workflow.`,
              head: branchName,
              base: 'main'
            });
            console.log(`Pull request created: ${result.data.html_url}`);
  
  send-slack-notification:
    needs: update-reference-date
    uses: ./.github/workflows/slack-webhook-message.yml
    with:
      action_runner: "ubuntu-latest"
      slack_message: "🔄 PR para atualização dos parâmetros do job criada!"
      environment: "production"  # Adjust this as needed
      custom_payload: |
        {
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "🔄 Reference Date Update PR Created",
                "emoji": true
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*A new PR has been created to update the Reference Date to ${{ needs.update-reference-date.outputs.next_monday }}*"
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*PR Link*\n<${{ needs.update-reference-date.outputs.pr_url }}|View Pull Request #${{ needs.update-reference-date.outputs.pr_number }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Workflow Run*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Repository*\n<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Triggered By*\n${{ github.event_name }}"
                }
              ]
            },
            {
              "type": "divider"
            },
            {
              "type": "context",
              "elements": [
                {
                  "type": "mrkdwn",
                  "text": "This is an automated notification from GitHub Actions."
                }
              ]
            }
          ]
        }
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
