name: Update Reference Date to Next Monday

on:
  schedule:
    # Runs every Thursday at 9:00 AM UTC
    - cron: '0 9 * * 3'
  # Optional: Allow manual workflow dispatch
  workflow_dispatch:

# Add these permissions
permissions:
  contents: write
  pull-requests: write
  
jobs:
  update-reference-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dateutil

      - name: Update reference date to next Monday
        id: update-date
        run: python .github/scripts/update_parameters.py
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update REFERENCE_DATE to ${{ steps.update-date.outputs.next_monday }}
          title: 'Update REFERENCE_DATE to ${{ steps.update-date.outputs.next_monday }}'
          body: |
            This automated PR updates the REFERENCE_DATE to the next Monday (${{ steps.update-date.outputs.next_monday }}).
            
            Automatically generated by the Update Reference Date workflow.
          branch: test-workflow-schedule
          base: main
